version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - db
    command: yarn run dev
    environment:
      NODE_ENV: development
  db:
    image: mongo
    ports:
      - "27017:27017"
