version: "3"
services:
  web:
    build: .
    image: marciaga/kffpadmin
    volumes:
      - ./:/opt/app
    ports:
      - "3000"
    command: bash -c "yarn && yarn build:production && yarn start"
    environment:
      NODE_ENV: production
    links:
      - db
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017"

  server:
    image: marciaga/kffp-nginx
    build: ./docker/nginx
    ports:
      - "80:80"
    links:
      - web
