version: "3"
services:
  web:
    build: .
    image: marciaga/kffpadmin
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      NODE_ENV: development
    command: yarn dev
    depends_on:
        - db
  db:
    image: mongo
    ports:
      - "27017:27017"
